config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Customer側devise
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }

  # Admin側devise
  devise_for :admin, :controllers => {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  # Admin側のルーティング設定
  namespace :admins do
    get "homes/top" => "homes#top"
    resources :items
    resources :customers
    resources :orders,only: [:show, :update]
    resources :genres,except: [:new,:destroy,:show]
    resources :order_details,only: [:update]
  end

  # customer側のルーティング設定
  # Top画面
  root 'public/items#top'
  get 'items' => 'public/items#about'

  namespace :public do
    get '/search' => 'search#search'

    resources :items, only: [:index, :show]

    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'all_destroy'
      end
    end

    # get=データを取得する処理、patch=情報を更新する(SQLでいうupdate)
    resources :customers,only: [:show, :edit, :update] do
      collection do
        get 'quit'
        patch 'out'
      end
    end
    # collection=　resourcesでは自動生成されないものに使う。生成するroutingに:idがつかない。


    resources :orders,only: [:new,:index,:show,:create] do
      collection do
        post 'to_log'
        get 'thanx'
      end
    end
    # post=URLが保存可、get=URL保存不可

    resources :addresses,only: [:index,:create,:destroy,:edit,:update]
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admins_genres_path
    else
      @genres = Genre.all
      render 'index'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admins_genres_path
    else
      render 'edit'
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/views/admins/genres/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <h5 class="two-line-heading">ジャンル編集</h5>
  </div>
  <div class="row mt-5">
    <div class="col">
      <%= form_with model: @genre, url: admins_genre_path(@genre.id), class:"form-inline", local: true do |f| %>
        <%= f.label :name, "ジャンル名", class:"form-group ml-1" %>
        <%= f.text_field :name, class:"form-group ml-5", placeholder: "ジャンル名" %>
        <%= f.submit '変更を保存', class:'btn-flat-success ml-5' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/genres/index.html.erb
<div class="container">
  <div class="row mt-5">
      <h5 class="two-line-heading">ジャンル一覧・追加</h5>
  </div>
  <div class="row mt-5">
    <div class="col">
      <%= form_with model: @genre, url: admins_genres_path, class:"form-inline", local: true do |f| %>
        <%= f.label :name, "ジャンル名", class:"form-group ml-1" %>
        <%= f.text_field :name, class:"form-group ml-5", placeholder: "ジャンル名" %>
        <%= f.submit '新規登録', class:'btn-flat-success ml-5' %>
      <% end %>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-md-5">
      <table class="table">
        <thead>
          <tr>
            <th>ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td class="d-flex justify-content-center"><%= link_to "編集する", edit_admins_genre_path(genre.id), class:"btn-flat-success" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>