config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Customer側devise
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }

  # Admin側devise
  devise_for :admin, :controllers => {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  # Admin側のルーティング設定
  namespace :admins do
    get "homes/top" => "homes#top"
    resources :items
    resources :customers
    resources :orders,only: [:show, :update]
    resources :genres,except: [:new,:destroy,:show]
    resources :order_details,only: [:update]
  end

  # customer側のルーティング設定
  # Top画面
  root 'public/items#top'
  get 'items' => 'public/items#about'

  namespace :public do
    get '/search' => 'search#search'

    resources :items, only: [:index, :show]

    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'all_destroy'
      end
    end

    # get=データを取得する処理、patch=情報を更新する(SQLでいうupdate)
    resources :customers,only: [:show, :edit, :update] do
      collection do
        get 'quit'
        patch 'out'
      end
    end
    # collection=　resourcesでは自動生成されないものに使う。生成するroutingに:idがつかない。


    resources :orders,only: [:new,:index,:show,:create] do
      collection do
        post 'to_log'
        get 'thanx'
      end
    end
    # post=URLが保存可、get=URL保存不可

    resources :addresses,only: [:index,:create,:destroy,:edit,:update]
  end

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :order_details
  has_many :cart_items, dependent: :destroy

  attachment :image

  # 消費税込みの値段表示
  def tax_include
    tax = 1.10
    (price * tax).round
  end

end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品の新規登録が完了しました"
      redirect_to admins_items_path
    else
      @genres = Genre.all
      render :new
    end
  end

  def index
     @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      @item.save
      flash[:notice] = "商品情報の更新が完了しました"
      redirect_to admins_items_path
    else
      @genres = Genre.all
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image, :is_active, :genre_id)
  end

end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/costomers/items_helper.rb
module Costomers::ItemsHelper
end

app/views/admins/items/edit.html.erb
<div class="container mt-5 mb-5">
  <div class="row mb-4">
    <h5 class="two-line-heading">商品編集</h5>
  </div>

  <%= form_with model: @item, url:admins_item_path(@item.id), local: true do |f| %>
    <div class="form_group row ml-10 mb-2">
      <%= f.label :商品画像, class:"col-sm-2 col-form-label" %>
        <div class="col-sm-10">
      　  <%= f.attachment_field :image %>
        </div>
  　</div>

    <div class="form_group row ml-10 mb-2">
      <%= f.label :商品名, class:"col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, size:"60" %>
      </div>
  　</div>

    <div class="form_group row ml-10 mb-2">
      <%= f.label :商品説明, class:"col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.text_area :caption, size:"60x10" %>
      </div>
  　 </div>

    <div class="form_group row ml-10 mb-4">
      <%= f.label :ジャンル, class:"col-sm-2 col-form-label"%>
      <div>
        <%= f.select :genre_id, @genres.map{ |genre| [genre.name, genre.id] }, {}, style:"width: 120px", class:"form-control ml-3" %>
      </div>
  　</div>

    <div class="form_group row ml-10 mb-2">
      <%= f.label :税抜価格, class:"col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.text_field :price %>円
      </div>
  　 </div>

    <div class="col text-center">
      <%= f.submit '変更を保存', class:"btn-flat-success ml-4"%>
    </div>
  <% end %>
</div>

app/views/admins/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col mt-3"><h5 class="two-line-heading">商品一覧</h5></div>

    <div class="btn-circle text-right">
      <div class="btn-outside">
        <div class="btn-text"><span class="fas fa-plus"></span></div>
        <div class="btn-click">
          <%= link_to "Add Item", new_admins_item_path %>
        </div>
      </div>
    </div>

    <table class="table table-hover w-100">
      <thead>
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name, admins_item_path(item), class:"link_animation" %></td>
          <!--数値を通過のフォーマットに変換-->
          <td><%= number_to_currency(item.price, format: "%u%n", unit: "¥", strip_insignificant_zeros: true) %></td>
          <td><%= item.genre.name %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @items %>
  </div>
</div>

app/views/admins/items/new.html.erb
<div class="container mt-5 mb-5">
  <div class="row mb-4">
    <h5 class="two-line-heading">新規商品登録</h5>
  </div>

  <%= form_with model: @item, url:admins_items_path, local: true do |f| %>
    <div class="form_group row ml-10 mb-2">
      <%= f.label :商品画像, class:"col-sm-2 col-form-label" %>
        <div class="col-sm-10">
      　  <%= f.attachment_field :item_image %>
        </div>
  　</div>

    <div class="form_group row ml-10 mb-2">
      <%= f.label :商品名, class:"col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, size:"60" %>
      </div>
  　</div>

    <div class="form_group row ml-10 mb-2">
      <%= f.label :商品説明, class:"col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.text_area :caption, size:"60x10" %>
      </div>
  　 </div>

    <div class="form_group row ml-10 mb-2">
      <%= f.label :ジャンル, class:"col-sm-2 col-form-label"%>
      <div class="col-sm-10">
        <%= f.select :genre_id, @genres.map{ |genre| [genre.name, genre.id] }, {}, style:"width: 120px", class:"form-control" %>
      </div>
  　</div>

    <div class="form_group row ml-10 mb-2">
      <%= f.label :税抜価格, class:"col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.text_field :price %>円
      </div>
  　</div>

    <div class="col text-center">
      <%= f.submit '新規登録', class:"btn-flat-success"%>
    </div>
  <% end %>
</div>

app/views/admins/items/show.html.erb
<div class="container">
  <div class="row">
    <h5 class="two-line-heading">商品詳細</h5>
  </div>

  <div class="card mb-3" style="max-width: 1000px;">
    <div class="row g-0">
      <div class="col-7">
        <%= attachment_image_tag @item, :image, hight:"100%", width:"100%" %>
      </div>
      <div class="col-5">
        <div class="card-body mt-4">

          <div class="row mb-3">
            <label class="col-sm-6">商品名</label>
            <div class="col-sm-6">
              <%= @item.name %>
            </div>
          </div>

          <div class="row mb-3">
            <label class="col-sm-6">商品説明</label>
            <div class="col-sm-6">
              <%= @item.introduction %>
            </div>
          </div>

          <div class="row mb-3">
            <label class="col-sm-6">ジャンル名</label>
            <div class="col-sm-6">
              <%= @item.genre.name %>
            </div>
          </div>

          <div class="row mb-3">
            <label class="col-sm-6">税込価格(税抜価格)</label>
            <div class="col-sm-6">
              <%= @item.tax_include %>(<%= @item.price %>)
            </div>
          </div>

          <div class="row">
            <div class="col-sm-5 offset-sm-6">
              <%= link_to "編集する", edit_admins_item_path(@item), class:"btn-flat-success ml-4" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>