config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Customer側devise
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }

  # Admin側devise
  devise_for :admin, :controllers => {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  # Admin側のルーティング設定
  namespace :admins do
    get "homes/top" => "homes#top"
    resources :items
    resources :customers
    resources :orders,only: [:show, :update]
    resources :genres,except: [:new,:destroy,:show]
    resources :order_details,only: [:update]
  end

  # customer側のルーティング設定
  # Top画面
  root 'public/items#top'
  get 'items' => 'public/items#about'

  namespace :public do
    get '/search' => 'search#search'

    resources :items, only: [:index, :show]

    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'all_destroy'
      end
    end

    # get=データを取得する処理、patch=情報を更新する(SQLでいうupdate)
    resources :customers,only: [:show, :edit, :update] do
      collection do
        get 'quit'
        patch 'out'
      end
    end
    # collection=　resourcesでは自動生成されないものに使う。生成するroutingに:idがつかない。


    resources :orders,only: [:new,:index,:show,:create] do
      collection do
        post 'to_log'
        get 'thanx'
      end
    end
    # post=URLが保存可、get=URL保存不可

    resources :addresses,only: [:index,:create,:destroy,:edit,:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
  
  #追加メソッド
  # 小計
  def subtotal
    self.amount * self.item.tax_include
  end
  
  # 合計
  def total
    cart_items=CartItem.where(customer_id: current_customer)
    cart_items.each do |cart_item|
      total_price + cart_item.subtotal
    end
    return total_price
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :order_details
  has_many :cart_items, dependent: :destroy

  attachment :image

  # 消費税込みの値段表示
  def tax_include
    tax = 1.10
    (price * tax).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { "クレジットカード": 0, "銀行振込": 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admins_genres_path
    else
      @genres = Genre.all
      render 'index'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admins_genres_path
    else
      render 'edit'
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品の新規登録が完了しました"
      redirect_to admins_items_path
    else
      @genres = Genre.all
      render :new
    end
  end

  def index
     @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      @item.save
      flash[:notice] = "商品情報の更新が完了しました"
      redirect_to admins_items_path
    else
      @genres = Genre.all
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image, :is_active, :genre_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/costomers/items_helper.rb
module Costomers::ItemsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">

      <%= link_to 'Fragrances Shop', root_path, class: "logo" %>
        <div class="navbar mt-4 nav-left" id="navbarToggleExternalContent">
          <% if customer_signed_in? %>
            <%= link_to 'My Page' ,class: "btn btn-outline-light nav-menu-text btn-sm" %>
            <%= link_to ' Item ', public_items_path, class: "btn btn-outline-info nav-menu-text ms-4 btn-sm" %>
            <%= link_to '　Cart　',  public_cart_items_path, class: "btn btn-outline-info ms-4 btn-sm" %>
            <%= link_to 'Logout', destroy_customer_session_path, method: :delete, class: "btn btn-outline-info nav-menu-text ms-4 me-4 btn-sm" %>
          <% elsif admin_signed_in? %>
            <%= link_to ' Item ', admins_items_path, class: "btn btn-outline-info nav-menu-text btn-sm" %>
            <%= link_to ' Member ', class: "btn btn-outline-light nav-menu-text ms-4 btn-sm " %>
            <%= link_to ' Order ', class: "btn btn-outline-light nav-menu-text ms-4 btn-sm " %>
            <%= link_to ' Genre ', admins_genres_path,class: "btn btn-outline-info ms-4 btn-sm" %>
            <%= link_to 'Logout', destroy_admin_session_path, method: :delete, class: "btn btn-outline-light nav-menu-text ms-4 me-4 btn-sm" %>
          <% else %>
            <%= link_to ' About ', items_path, class: "btn btn-outline-info btn-sm" %>
            <%= link_to ' Item ', public_items_path, class: "btn btn-outline-light ms-4 btn-sm" %>
            <%= link_to ' Signup ', new_customer_registration_path,class: "btn btn-outline-info ms-4 btn-sm" %>
            <%= link_to ' Login ', new_customer_session_path,class: "btn btn-outline-info ms-4 btn-sm" %>
          <% end %>
        </div>
        <nav class="navbar navbar-dark bg-dark header-nav mt-0" media="screen and (max-width: 480px)">
          <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          </div>
        </nav>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ec</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>